name: Test Orca IaC action

on:
  workflow_dispatch:
  pull_request:

jobs:
  iac_scan_job:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Scan IaC
        uses: orcasecurity/shiftleft-iac-action@v1
        with:
          api_token:
            ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key:
            "default"
          path:
            "."
          format:
            "sarif"
          output:
            "results/"
          console_output: "cli"
          custom_controls: "custom_query"
          generate_rego_input: "blablab.json"
          show_annotations: false
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: results/iac.sarif
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: orca-results
          path: |
            results/
            blablab.json
            
